
# Additional prefixes for the Instance
prefixes = ['easy']
bool_true_list = ['1', 'yes', 'y', 'true']
bool_false_list = ['0', 'no', 'n', 'false']

# Translations of the ezbotf Instance
instance.nonexistent_command  = "**Command isn't exists!**"
instance.disallow_access      = '**You have not access to this command!**'

# Translations of the ezbotf ArgumentParser
argumentparser.too_little_arguments        = '**There is too little arguments!**'
argumentparser.too_many_arguments          = '**There is too many arguments!**'
argumentparser.reply_to_required           = '**To use this command, you must reply to any message**'
argumentparser.incorrect_type              = '**Incorrect data type of argument**'
argumentparser.incorrect_subcommand        = '**There is no that subcommand**'
argumentparser.cant_find_original_message  = '**Cant find original message from reply. Limit of distance between messages is** `50` **messages**'
argumentparser.plugin_error                = '**Plugin returned an exception.**\n\nYou may check the console (**if log level is** `exception`+) for the error'
